services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        command: php-fpm

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        ports:
            - "${APP_PORT}:80"
            - "443:443"
        depends_on:
            - app
        networks:
            - laravel_network
        environment:
            - SERVER_NAME=${APP_DOMAIN}
            - PORT=${APP_PORT}

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        networks:
            - laravel_network

    mongo:
        image: mongo:8
        container_name: mongo_db
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - mongo_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    mongo_data:
